// Utilities
import { defineStore } from "pinia";
// Generated by https://quicktype.io

export interface Config {
  theme:                Theme;
  logo:                 Logo;
  background:           Background;
  welcome_information:  TermsAndConditions;
  terms_and_conditions: TermsAndConditions;
  top_nav:              TopNav;
  authorization:        Authorization;
}

export interface Authorization {
  methods: Method[];
}

export interface Method {
  type:   string;
  enable: boolean;
  text:   string;
  icon:   string;
}

export interface Background {
  isBackground:      boolean;
  background:        string;
  backgroundOpacity: number;
  backgroundColor:   string;
}

export interface Logo {
  isLogo:     boolean;
  logo:       string;
  logoSize:   number;
  text:       string;
  textSize:   number;
  textColor:  string;
  textFont:   string;
  textBold:   boolean;
  textItalic: boolean;
  margin:     Margin;
}

export interface Margin {
  top:    number;
  bottom: number;
  left:   number;
  right:  number;
}

export interface TermsAndConditions {
  isTermsAndConditions?: boolean;
  text:                  string;
  textSize:              number;
  textColor:             string;
  textFont:              string;
  textBold:              boolean;
  textItalic:            boolean;
  url?:                  string;
  isWelcomeInformation?: boolean;
}

export interface Theme {
  LoginButton: LoginButton;
  input:       Input;
}

export interface LoginButton {
  textColor:  string;
  textFont:   string;
  textBold:   boolean;
  textItalic: boolean;
  color:      string;
  text:       string;
}

export interface Input {
  textColor:  string;
  textFont:   string;
  textBold:   boolean;
  textItalic: boolean;
  Color:      string;
}

export interface TopNav {
  isTopNav: boolean;
  links:    Link[];
}

export interface Link {
  text: string;
  url:  string;
}


export const useAppStore = defineStore("app", {
  state: () => ({
    config: {
      authorization: {
        methods: [] as Method[],
      },
      background: {
        isBackground: false,
        background: "",
        backgroundOpacity: 0,
        backgroundColor: "",
      },
      logo: {
        isLogo: false,
        logo: "",
        logoSize: 0,
        text: "",
        textSize: 0,
        textColor: "",
        textFont: "",
        textBold: false,
        textItalic: false,
        margin: {
          top: 0,
          bottom: 0,
          left: 0,
          right: 0,
        },
      } as Logo,
      termsAndConditions: {
        isTermsAndConditions: false,
        text: "",
        textSize: 0,
        textColor: "",
        textFont: "",
        textBold: false,
        textItalic: false,
        url: "",
        isWelcomeInformation: false,
      },
      theme: {
        LoginButton: {
          textColor: "",
          textFont: "",
          textBold: false,
          textItalic: false,
          color: "",
          text: "",
        },
        input: {
          textColor: "",
          textFont: "",
          textBold: false,
          textItalic: false,
          Color: "",
        },
      },
      top_nav: {
        isTopNav: false,
        links: [] as Link[],
      },
    },
  }) ,
  getters: {
    //
  },
  actions: {
    fetchSettings() {
      return fetch("/config.json")
        .then((response) => {
          return response.json();
        })
        .then((data) => {
          this.config = data;
          return data;
        });
    },
  },
});
