/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    AuthBackgoung: typeof import('./components/Auth/Backgoung.vue')['default']
    AuthCredentials: typeof import('./components/Auth/Credentials.vue')['default']
    AuthForm: typeof import('./components/AuthForm.vue')['default']
    AuthFree: typeof import('./components/Auth/Free.vue')['default']
    AuthOtp: typeof import('./components/Auth/Otp.vue')['default']
    AuthQr: typeof import('./components/Auth/Qr.vue')['default']
    AuthVoucher: typeof import('./components/Auth/Voucher.vue')['default']
    Form: typeof import('./components/Form.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    TermsOfService: typeof import('./components/TermsOfService.vue')['default']
  }
}
